# GitHub Pages configuration
# Force proper MIME types for JavaScript modules
plugins:
  - jekyll-optional-front-matter

# Ensure proper MIME types
defaults:
  - scope:
      path: "assets"
    values:
      content-type: "application/javascript"

# Include all files (don't exclude anything)
include:
  - _headers
  - .nojekyll

# Exclude unnecessary files
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - vite.config.ts
  - tsconfig.json
  - README.md
